import nodemailer from 'nodemailer';

export async function sendEmailNotification(summary, stats, markdownReport, config) {
  const { smtp_host, smtp_port, smtp_user, smtp_pass, to } = config;
  if (!smtp_host || !to) throw new Error('email.smtp_host and email.to are required');

  const transporter = nodemailer.createTransport({
    host: smtp_host,
    port: smtp_port ?? 587,
    secure: (smtp_port ?? 587) === 465,
    auth: smtp_user ? { user: smtp_user, pass: smtp_pass } : undefined,
  });

  const highlights = summary.highlights?.map((h) => `<li>${h}</li>`).join('') ?? '';

  const html = `
    <html><body style="font-family:monospace;background:#0d0d0d;color:#e8e8e8;padding:24px;max-width:720px">
      <h2 style="color:#e8813a">⚡ GitPulse Report</h2>
      <table style="border-collapse:collapse;margin-bottom:16px">
        <tr>
          <td style="padding:8px 16px 8px 0;color:#888">Commits</td><td style="padding:8px 16px 8px 0">${stats.totalCommits}</td>
          <td style="padding:8px 16px 8px 0;color:#888">Authors</td><td style="padding:8px 16px 8px 0">${stats.totalAuthors}</td>
          <td style="padding:8px 16px 8px 0;color:#888">Repos</td><td>${stats.totalRepos}</td>
        </tr>
        <tr>
          <td style="color:#888">Lines</td>
          <td colspan="5"><span style="color:#4caf7d">+${stats.totalInsertions}</span> / <span style="color:#e05a5a">-${stats.totalDeletions}</span></td>
        </tr>
      </table>
      <h3 style="color:#888;text-transform:uppercase;font-size:11px;letter-spacing:0.1em">Summary (${summary.style})</h3>
      <p style="white-space:pre-wrap;line-height:1.7">${summary.overall ?? ''}</p>
      ${highlights ? `<h3 style="color:#888;text-transform:uppercase;font-size:11px;letter-spacing:0.1em">Highlights</h3><ul>${highlights}</ul>` : ''}
      <hr style="border-color:#2a2a2a;margin:24px 0"/>
      <p style="color:#888;font-size:11px">Generated by GitPulse · ${new Date().toISOString()}</p>
    </body></html>
  `;

  await transporter.sendMail({
    from: smtp_user ?? 'gitpulse@localhost',
    to,
    subject: `GitPulse Report — ${new Date().toLocaleDateString()}`,
    html,
    attachments: markdownReport
      ? [{ filename: 'gitpulse-report.md', content: markdownReport }]
      : [],
  });
}
