import { IncomingWebhook } from '@slack/webhook';

export async function sendSlackNotification(summary, stats, config) {
  const { webhook_url, style } = config;
  if (!webhook_url) throw new Error('slack.webhook_url is required');

  const webhook = new IncomingWebhook(webhook_url);

  const highlights = summary.highlights?.map((h) => `• ${h}`).join('\n') ?? '';

  await webhook.send({
    blocks: [
      {
        type: 'header',
        text: { type: 'plain_text', text: '⚡ GitPulse Report', emoji: true },
      },
      {
        type: 'section',
        fields: [
          { type: 'mrkdwn', text: `*Commits*\n${stats.totalCommits}` },
          { type: 'mrkdwn', text: `*Authors*\n${stats.totalAuthors}` },
          { type: 'mrkdwn', text: `*Repos*\n${stats.totalRepos}` },
          { type: 'mrkdwn', text: `*Lines*\n+${stats.totalInsertions} / -${stats.totalDeletions}` },
        ],
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Summary (${style})*\n${summary.overall?.slice(0, 2800) ?? ''}`,
        },
      },
      highlights
        ? { type: 'section', text: { type: 'mrkdwn', text: `*Highlights*\n${highlights}` } }
        : null,
      {
        type: 'context',
        elements: [
          { type: 'mrkdwn', text: `Generated by GitPulse · ${new Date().toISOString()}` },
        ],
      },
    ].filter(Boolean),
  });
}
